services:

  finverse-api:

    build:
      context: ./backend/FinVerse.API

    container_name: finverse-api

    restart: always

    ports:
      - "8080:8080"

    environment:
      ConnectionStrings__DefaultConnection: Host=finverse-db-1.c4v6wisem889.us-east-1.rds.amazonaws.com;Port=5432;Database=finverse_db;Username=postgres;Password=YOUR_RDS_PASSWORD;SSL Mode=Require;Trust Server Certificate=true

  finverse-frontend:

    build:
      context: ./frontend

    container_name: finverse-frontend

    restart: always

    depends_on:
      - finverse-api

    ports:
      - "3000:3000"

    environment:
      NEXT_PUBLIC_API_URL: https://api.meghrajrathod.cloud