- name: Configure FinVerse Server

  hosts: finverse_servers

  become: true

  tasks:

    - name: Update packages

      yum:

        name: "*"

        state: latest

    - name: Install Git

      yum:

        name: git

        state: present

    - name: Install Docker

      yum:

        name: docker

        state: present

    - name: Start Docker

      service:

        name: docker

        state: started

        enabled: true

    - name: Add ec2-user to docker group

      user:

        name: ec2-user

        groups: docker

        append: yes

    - name: Install Docker Compose

      get_url:

        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64

        dest: /usr/local/bin/docker-compose

        mode: '0755'

    - name: Clone FinVerse Repository

      git:

        repo: https://github.com/meghrajrathod/FinVerse-DevOps.git

        dest: /home/ec2-user/FinVerse-DevOps

        version: master

        force: yes

    - name: Start Docker Containers

      shell: |

        cd /home/ec2-user/FinVerse-DevOps

        docker compose up --build -d