name: FinVerse CI Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ./backend/FinVerse.API

      - name: Build Project
        run: dotnet build --no-restore
        working-directory: ./backend/FinVerse.API

      - name: Publish Project
        run: dotnet publish -c Release -o out
        working-directory: ./backend/FinVerse.API

      - name: Build Docker Image
        run: docker build -t finverse-api .
        working-directory: ./backend/FinVerse.API